# config/database.yml

staging: &defaults
  adapter: postgresql
  encoding: utf8
  database: blogtp_staging
  pool: 5
  username: enbake
  password: admin
  host: 127.0.0.1

test:
  <<: *defaults
  database: blogtp_test

production:
  <<: *defaults
  database: blogtp_production

development:
  <<: *defaults
  database: blogtp_development
